@startuml  konceptualny
entity album{
  * name
}

entity photo{
  * reference
  * likes
  * dislikes
  * views
  * title
  * description
  * location
}

entity tag{
  * name
}

entity comment{
  * user
  * content
  * date
}


photo }|-- album
comment }|-- photo
tag }|-- photo
@enduml
